### ISSUE TITLE
the example project seems to be missing stuff

### ISSUE THREAD

**Issue by hannesdelbeke** [bhowiebkr/python-node-editor#7]
by default if i press the button in the example project
a exception is raised, since compute is not implemented.

if i override the compute on the [button node](https://github.com/bhowiebkr/python-node-editor/blob/master/Example_Project/Button_node.py) to avoid the exception
it only executes the current node. since run_output_nodes doesnt do anyhting.

**Comment by hannesdelbeke** [comment]
your comment in https://github.com/bhowiebkr/python-node-editor/discussions/2 clarified this project is not finished.

**Comment by bhowiebkr** [comment]
Sorry yeah I don’t have compute code implemented yet, started but not finished. When I get some time I’ll see about finishing that portion of the system. 

In the meantime If anyone wants to take a crack at it and do a pull request that’d be great!

**Comment by hannesdelbeke** [comment]
no worries.
i decided to use http://chantonic.com/NodeGraphQt/api/index.html since it has more features.
it's also UI only, so I'm implementing my own compute
